### ISSUE TITLE
WebGL/WebAssembly

### ISSUE THREAD

**Issue by dakom** [tyt2y3/vaserenderer#4]
I'm just doing a bit of R&D into line-drawing with WebGL, specifically with textured brushes... ended up here via https://mattdesl.svbtle.com/drawing-lines-is-hard

With that in mind (that I haven't really dug into your code yet) - what are your thoughts on portability to WebGL+WebAssembly?

Are there any showstoppers that would make this effort futile?

Thanks!

**Comment by tyt2y3** [comment]
I think Konstantin Käfer has written a [great article](https://blog.mapbox.com/drawing-antialiased-lines-with-opengl-8766f34192dc) outlining the work he has done in [MapBoxGL](https://github.com/mapbox/mapbox-gl-js). Many ideas in my original articles were discussed thoroughly and adapted to a more shader-friendly implementation. I recommend you to check there.

Speaking on WebAssembly, yes, I think you can compile the code and run it inside the browser via an OpenGL 2.0 compatibility layer (remember **not** OpenGL ES 2.0), reason being the current code is not using VBO but VA. Even if you managed to solve all these, performance-wise it won't be as good as MapBox, as the latter has some trade offs and redesigned for WebGL.

If you want textured strokes, VASEr will be a better bet as the triangulation in MapBox is too stripped-off in some cases. 

Hope this helps, Chris
