### ISSUE TITLE
Tesselation wrong

### ISSUE THREAD

**Issue by nidefawl** [tyt2y3/vaserenderer#5]
I have some issues with tesselation. I'm not certain whats going on, but I only see the issues with some of the data I want to render.
![polyline_2018-02-01_23-03-59](https://user-images.githubusercontent.com/637382/35706088-c1628b60-07a4-11e8-921d-6e6c64ad94a9.png)

When I reduce the line thickness the artifact goes away. This artifact also goes away if I change or scale the input data.
![polyline_2018-02-01_23-04-10](https://user-images.githubusercontent.com/637382/35706091-c377075a-07a4-11e8-8f42-c8165e1b5878.png)

I confirmed that it is wrong data tesselated by VASEr, not an opengl issue.
I prepared a testcase on the sample application:
https://github.com/nidefawl/vaserenderer/commit/edcb5c7840776c21535993c990c95a15cca7cdc1

Here is a zoomed up view including triangulation higlights.
![glfwtest_2018-02-01_23-01-15](https://user-images.githubusercontent.com/637382/35706210-2c16ac8e-07a5-11e8-856e-4bf93ff67bc9.png)
Slightly increased line thickness:
![glfwtest_2018-02-01_23-03-06](https://user-images.githubusercontent.com/637382/35706212-2d5d9e54-07a5-11e8-9b78-81a94ad9863a.png)

**Comment by tyt2y3** [comment]
Thank you for reporting. I can confirm with you that this is indeed a geometric calculation error somewhere. When there is a test case, though, with the help of a debugger, one can step through and see where the error happens.
